### PR TITLE
Version bump, Fixed plugin.

### PR DESCRIPTION
**Pull request by Akuba-**
Version bump to 2.2.
Trancparency patcher is working again.

### CODE REVIEW

**Comment by holly-hacker** [comment]
The transparency patcher should only modify the files on disk to allow for transparent windows, giving elements actual transparency is the job of the [Transparency plugin](https://github.com/HoLLy-HaCKeR/BetterDiscord-Themes-and-Plugins/blob/master/Themes/Transparency.md). Can you look into using just themes for this patch?

**Comment by Akuba-** [comment]
I tried this before but it doesn't look like I am able to modify "backgroundColor" with themes, Discord will keep it's black background. On the other hand, I am not that experienced with themes at all, so there might be a way.

**Comment by holly-hacker** [comment]
I can't verify that this works or look for a theme way right now, so I won't merge this yet. I'll try to set up a testing environment in the near future so I can, though.

**Comment by holly-hacker** [comment]
Merging since it fixes #6.

**Pull request merged**
